-- MySQL schema for geo-track admin hub
-- Create required tables and add missing columns if needed (MySQL 8.0+)

-- Clients table
CREATE TABLE IF NOT EXISTS clients (
  client_id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  full_name VARCHAR(150) NULL,
  email VARCHAR(255) NULL,
  phone_number VARCHAR(50) NULL,
  is_admin TINYINT(1) NOT NULL DEFAULT 0,
  statut ENUM('active','disabled') DEFAULT 'active',
  last_login DATETIME NULL,
  nbr_phones INT DEFAULT 0,
  expire_date DATE NULL,
  PRIMARY KEY (client_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Add columns to existing clients table if they do not exist
ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS client_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ADD COLUMN IF NOT EXISTS username VARCHAR(100) NOT NULL UNIQUE,
  ADD COLUMN IF NOT EXISTS password VARCHAR(255) NOT NULL,
  ADD COLUMN IF NOT EXISTS full_name VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS email VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS phone_number VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS is_admin TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS statut ENUM('active','disabled') DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS last_login DATETIME NULL,
  ADD COLUMN IF NOT EXISTS nbr_phones INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS expire_date DATE NULL;

-- Phones table
CREATE TABLE IF NOT EXISTS phones (
  phone_id VARCHAR(64) NOT NULL,
  phone_name VARCHAR(150) NOT NULL,
  client_id INT NOT NULL,
  last_update DATETIME NULL,
  PRIMARY KEY (phone_id),
  KEY idx_phones_client_id (client_id),
  CONSTRAINT fk_phones_client
    FOREIGN KEY (client_id) REFERENCES clients(client_id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Locations table
CREATE TABLE IF NOT EXISTS locations (
  id BIGINT NOT NULL AUTO_INCREMENT,
  phone_id VARCHAR(64) NOT NULL,
  latitude DECIMAL(10,7) NOT NULL,
  longitude DECIMAL(10,7) NOT NULL,
  date_time DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_locations_phone_time (phone_id, date_time),
  CONSTRAINT fk_locations_phone
    FOREIGN KEY (phone_id) REFERENCES phones(phone_id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- BON1 table (sales/orders) with device linkage
CREATE TABLE IF NOT EXISTS BON1 (
  RECORDID INT NULL,
  NUM_BON VARCHAR(100) NOT NULL,
  CODE_CLIENT VARCHAR(100) NULL,
  DATE_BON VARCHAR(32) NULL,
  HEURE VARCHAR(32) NULL,
  DATE_F VARCHAR(32) NULL,
  HEURE_F VARCHAR(32) NULL,
  NBR_P INT NULL,
  TOT_QTE DOUBLE NULL,
  MODE_TARIF VARCHAR(50) NULL,
  CODE_DEPOT VARCHAR(50) NULL,
  MODE_RG VARCHAR(50) NULL,
  CODE_VENDEUR VARCHAR(50) NULL,
  TOT_HT DOUBLE NULL,
  TOT_TVA DOUBLE NULL,
  TIMBRE DOUBLE NULL,
  TIMBRE_CHECK VARCHAR(10) NULL,
  LATITUDE DECIMAL(10,7) NOT NULL DEFAULT 0,
  LONGITUDE DECIMAL(10,7) NOT NULL DEFAULT 0,
  REMISE DOUBLE NULL,
  MONTANT_ACHAT DOUBLE NULL,
  ANCIEN_SOLDE DOUBLE NULL,
  EXPORTATION VARCHAR(50) NULL,
  BLOCAGE VARCHAR(50) NULL,
  VERSER DOUBLE NULL,
  LIVRER INT NOT NULL DEFAULT 0,
  DATE_LIV VARCHAR(32) NULL,
  IS_IMPORTED TINYINT(1) NOT NULL DEFAULT 0,
  IS_EXPORTED TINYINT(1) NOT NULL DEFAULT 0,
  phone_id VARCHAR(64) NOT NULL,
  PRIMARY KEY (NUM_BON),
  KEY idx_bon1_phone_id (phone_id),
  CONSTRAINT fk_bon1_phone
    FOREIGN KEY (phone_id) REFERENCES phones(phone_id)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- BON2 table (order line items) linked to BON1
CREATE TABLE IF NOT EXISTS BON2 (
  RECORDID BIGINT NOT NULL AUTO_INCREMENT,
  CODE_BARRE VARCHAR(100) NULL,
  NUM_BON VARCHAR(100) NOT NULL,
  PRODUIT VARCHAR(255) NULL,
  NBRE_COLIS DOUBLE NULL,
  COLISSAGE DOUBLE NULL,
  QTE_GRAT DOUBLE NULL,
  QTE DOUBLE NULL,
  PV_HT DOUBLE NULL,
  PA_HT DOUBLE NULL,
  DESTOCK_TYPE VARCHAR(50) NULL,
  DESTOCK_CODE_BARRE VARCHAR(100) NULL,
  DESTOCK_QTE DOUBLE NULL,
  TVA DOUBLE NULL,
  CODE_DEPOT VARCHAR(50) NULL,
  PRIMARY KEY (RECORDID),
  KEY idx_bon2_num_bon (NUM_BON),
  KEY idx_bon2_code_barre (CODE_BARRE),
  CONSTRAINT fk_bon2_bon
    FOREIGN KEY (NUM_BON) REFERENCES BON1(NUM_BON)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- BON1_TEMP table (temporary sales/orders) with device linkage
CREATE TABLE IF NOT EXISTS BON1_TEMP (
  RECORDID INT NULL,
  NUM_BON VARCHAR(100) NOT NULL,
  CODE_CLIENT VARCHAR(100) NULL,
  DATE_BON VARCHAR(32) NULL,
  HEURE VARCHAR(32) NULL,
  DATE_F VARCHAR(32) NULL,
  HEURE_F VARCHAR(32) NULL,
  NBR_P INT NULL,
  TOT_QTE DOUBLE NULL,
  MODE_TARIF VARCHAR(50) NULL,
  CODE_DEPOT VARCHAR(50) NULL,
  MODE_RG VARCHAR(50) NULL,
  CODE_VENDEUR VARCHAR(50) NULL,
  TOT_HT DOUBLE NULL,
  TOT_TVA DOUBLE NULL,
  TIMBRE DOUBLE NULL,
  TIMBRE_CHECK VARCHAR(10) NULL,
  LATITUDE DECIMAL(10,7) NOT NULL DEFAULT 0,
  LONGITUDE DECIMAL(10,7) NOT NULL DEFAULT 0,
  REMISE DOUBLE NULL,
  MONTANT_ACHAT DOUBLE NULL,
  ANCIEN_SOLDE DOUBLE NULL,
  EXPORTATION VARCHAR(50) NULL,
  BLOCAGE VARCHAR(50) NULL,
  VERSER DOUBLE NULL,
  LIVRER INT NOT NULL DEFAULT 0,
  DATE_LIV VARCHAR(32) NULL,
  IS_IMPORTED TINYINT(1) NOT NULL DEFAULT 0,
  IS_EXPORTED TINYINT(1) NOT NULL DEFAULT 0,
  phone_id VARCHAR(64) NOT NULL,
  PRIMARY KEY (NUM_BON),
  KEY idx_bon1temp_phone_id (phone_id),
  CONSTRAINT fk_bon1temp_phone
    FOREIGN KEY (phone_id) REFERENCES phones(phone_id)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- BON2_TEMP table (temporary order line items) linked to BON1_TEMP
CREATE TABLE IF NOT EXISTS BON2_TEMP (
  RECORDID BIGINT NOT NULL AUTO_INCREMENT,
  CODE_BARRE VARCHAR(100) NULL,
  NUM_BON VARCHAR(100) NOT NULL,
  PRODUIT VARCHAR(255) NULL,
  NBRE_COLIS DOUBLE NULL,
  COLISSAGE DOUBLE NULL,
  QTE_GRAT DOUBLE NULL,
  QTE DOUBLE NULL,
  PV_HT DOUBLE NULL,
  PA_HT DOUBLE NULL,
  DESTOCK_TYPE VARCHAR(50) NULL,
  DESTOCK_CODE_BARRE VARCHAR(100) NULL,
  DESTOCK_QTE DOUBLE NULL,
  TVA DOUBLE NULL,
  CODE_DEPOT VARCHAR(50) NULL,
  PRIMARY KEY (RECORDID),
  KEY idx_bon2temp_num_bon (NUM_BON),
  KEY idx_bon2temp_code_barre (CODE_BARRE),
  CONSTRAINT fk_bon2temp_bon
    FOREIGN KEY (NUM_BON) REFERENCES BON1_TEMP(NUM_BON)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Helpful example: insert a demo client with hashed password
-- Replace HASHED_PASSWORD with a bcrypt hash
-- INSERT INTO clients (username, password, full_name, email, phone_number, statut, last_login, nbr_phones, expire_date)
-- VALUES ('demo', 'HASHED_PASSWORD', 'Demo User', 'demo@example.com', '0000000000', 'active', NOW(), 0, DATE_ADD(CURDATE(), INTERVAL 1 YEAR));